<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="TrackingDifferentiator" Id="{ec373d2a-a4bc-40dc-87dc-df17586bf4df}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION TrackingDifferentiator :LREAL

VAR_INPUT
	expect:LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[v1 := v1 + ADRC_TD_h0 * v2;//跟新最速跟踪状态量x1
v2 := v2 + ADRC_TD_h0 * (-ADRC_TD_r0 * Sign(v1 - expect + (v2 * ABS(v2))/(2 * ADRC_TD_r0)));//跟新最速跟踪状态量微分x2]]></ST>
    </Implementation>
    <LineIds Name="TrackingDifferentiator">
      <LineId Id="5" Count="0" />
      <LineId Id="13" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>